/**
 * Auto-generated Alt Text Mapping
 * Generated by: scripts/generate-alt-text-gemini.js
 * Last updated: 2025-12-11T12:41:16.131Z
 * 
 * Usage:
 *   import { getAltText } from './altTextMap';
 *   <img src={imagePath} alt={getAltText(imagePath)} />
 */

export const altTextMap: Record<string, string> = {
  '/credit-cards/amazon-business-prime.png': 'Amazon Business Prime American Express card image for business credit card reviews.',
  '/credit-cards/amex-blue-business-cash.png': 'American Express Blue Business Cash card with blue design for business expenses.',
  '/credit-cards/amex-business-gold.png': 'American Express Business Gold Card. Textured gold credit card, Amex rewards and benefits.',
  '/credit-cards/amex-business-platinum.png': 'American Express Business Platinum card image: brushed silver design, business credit card.',
  '/credit-cards/amex-everyday.png': 'Amex Everyday credit card in hand. American Express card for building credit.',
  '/credit-cards/amex-gold.png': 'American Express Gold Card image: Metal design for rewards and travel points.',
  '/credit-cards/amex-green.png': 'American Express Green card. A popular travel rewards credit card.',
  '/credit-cards/amex-platinum.png': 'American Express Platinum card featuring a silver metal design and Amex logo.',
  '/credit-cards/bankamericard.png': 'Bank of America credit card. White card with abstract design and Mastercard logo.',
  '/credit-cards/blue-business-plus.png': 'American Express Blue Business Plus credit card with blue and silver design.',
  '/credit-cards/blue-cash-everyday.png': 'Blue Cash Everyday card from American Express: cash back rewards card.',
  '/credit-cards/blue-cash-preferred.png': 'American Express Blue Cash Preferred Card. Blue card with Centurion design.',
  '/credit-cards/capital-one-venture-x.png': 'Capital One Venture X Business credit card with sleek design. Travel rewards.',
  '/credit-cards/chase-sapphire-preferred.png': 'Chase Sapphire Preferred credit card with blue design and Visa logo.',
  '/credit-cards/chase-slate-edge.png': 'Chase Slate Edge credit card with blue design and Visa logo.',
  '/credit-cards/citi-diamond-preferred.png': 'Citi Diamond Preferred credit card, black geometric design, Mastercard, from Citibank.',
  '/credit-cards/citi-double-cash.png': 'Citi Double Cash credit card with blue and green design, cash back rewards.',
  '/credit-cards/delta-skymiles-gold.png': 'Delta SkyMiles Gold American Express card for travel rewards and airline miles.',
  '/credit-cards/delta-skymiles-reserve.png': 'Delta SkyMiles Reserve American Express card with purple design for travel rewards.',
  '/credit-cards/discover-it-balance-transfer.png': 'Discover it Balance Transfer credit card with orange sun design.',
  '/credit-cards/hilton-honors-aspire.png': 'Hilton Honors Aspire card from American Express. Blue travel rewards credit card.',
  '/credit-cards/us-bank-visa-platinum.png': 'US Bank Visa Platinum credit card image. Gray card with red accent.',
  '/credit-cards/wells-fargo-reflect.png': 'Wells Fargo Reflect Visa credit card, close up view of red design.',
  '/insurance-logos/allstate.png': 'Allstate Insurance logo: A handshake icon with the Allstate company name.',
  '/insurance-logos/amica.png': 'Amica Insurance logo variations: various blue wordmarks and design elements.',
  '/insurance-logos/chubb.png': 'Chubb Insurance logo. Gold and black text with shield icon. Insurance provider.',
  '/insurance-logos/erie.png': 'Erie Insurance logo: Blue text with distinctive E icon for home and auto coverage.',
  '/insurance-logos/farmers.png': 'Farmers Insurance logo: Red and blue shield icon for home, auto, life insurance.',
  '/insurance-logos/geico.png': 'Geico Insurance logo featuring a green gecko, for car, home, and life policies.',
  '/insurance-logos/havenlife.png': 'Haven Life Insurance logo: Light blue lettering with abstract H graphic.',
  '/insurance-logos/lemonade.png': 'Lemonade Insurance logo: Pink grapefruit slice, letter L designs, modern insurance provider.',
  '/insurance-logos/libertymutual.png': 'Liberty Mutual insurance logo: Torch symbol for home, car, and life insurance.',
  '/insurance-logos/massmutual.png': 'MassMutual insurance logo with blue "M" icon and company name.',
  '/insurance-logos/metlife.png': 'MetLife insurance logo: "ML" icon in blue/green, rainbow arch icon, company name.',
  '/insurance-logos/nationwide.png': 'Nationwide Insurance logo: stylized eagle head in red, financial services provider.',
  '/insurance-logos/newyorklife.png': 'New York Life insurance logo with the Statue of Liberty icon.',
  '/insurance-logos/northwestern.png': 'Northwestern Mutual insurance logo: Blue stylized N and NM in shield.',
  '/insurance-logos/progressive.png': 'Progressive Insurance logo: Blue arrow icon with brand name for car & home insurance.',
  '/insurance-logos/prudential.png': 'Prudential insurance company logo featuring the Rock of Gibraltar in blue tones.',
  '/insurance-logos/statefarm.png': 'State Farm Insurance logo with red oval design and company name.',
  '/insurance-logos/travelers.png': 'Travelers Insurance logo: Red umbrella icon above company name.',
  '/insurance-logos/usaa.png': 'USAA logo: Blue shield with gold eagle head, representing insurance and financial services.',
  '/life-insurance-logos/aflac.png': 'Aflac Insurance logo: Blue duck icon representing supplemental insurance coverage.',
  '/life-insurance-logos/john-hancock.png': 'John Hancock Insurance logo: Elegant signature of the company name in black.',
  '/life-insurance-logos/lincoln-financial.png': 'Lincoln Financial Group logo featuring Abraham Lincoln\'s silhouette, insurance provider.',
  '/life-insurance-logos/metlife.png': 'MetLife insurance logo: Blue and green abstract shapes with black "MetLife" text.',
  '/life-insurance-logos/new-york-life.png': 'New York Life Insurance company logo, white text on black square background.',
  '/life-insurance-logos/prudential.png': 'Prudential Financial logo: Text and rock of Gibraltar icon for insurance company.',
  '/life-insurance-logos/state-farm.png': 'State Farm Insurance logo with interlocking red circles on green background.',
  '/blog-images/airport-lounge.jpg': 'Air Canada airplane preparing to land; related to travel rewards credit cards.',
  '/blog-images/american-airlines-flagship.jpg': 'American Airlines wing against sky, travel rewards from credit card points.',
  '/blog-images/chase-comparison.jpg': 'Man holding credit card using laptop for online shopping or payments.',
  '/blog-images/chase-rewards.jpg': 'Laptop screen showing how to increase revenue with email form.',
  '/blog-images/credit-card-comparison.jpg': 'Customer using phone for credit card purchase at POS terminal.',
  '/blog-images/default-article.jpg': 'Preparing taxes: Woman calculates taxes with forms, calculator app, and pen.',
  '/blog-images/delta-plane.jpg': 'Private jet airplane on tarmac at sunset, consider travel rewards cards.',
  '/blog-images/extended-warranty.jpg': 'Customer uses phone to pay a store clerk at point of sale.',
  '/blog-images/hawaii-beach.jpg': 'Hawaii travel: Waikiki beach view with Diamond Head, plan your points travel.',
  '/blog-images/hotel-lobby.jpg': 'Hotel pool and lounge chairs: travel rewards or vacation planning content.',
  '/blog-images/hyatt-tokyo.jpg': 'Tokyo\'s Akihabara district, illuminated by neon lights, for travel rewards inspiration.',
  '/blog-images/park-hyatt.jpg': 'Luxury travel rewards at an oceanfront resort with a pool and lounge chairs.',
  '/blog-images/rewards-points.jpg': 'Person using a credit card and laptop, earning rewards points.',
  '/blog-images/travel-credit-cards.jpg': 'Laptop displays an ebook offer, "increase revenue" for finance or travel business.',
  '/blog-images/warranty-protection.jpg': 'Close up of person signing a financial warranty protection document.',
  '/category-images/balance-transfer.jpeg': 'Balance transfer credit cards: Arrows indicate transferring balances between two cards.',
  '/category-images/business.jpeg': 'Briefcase, tablet with graph, and credit cards representing financial planning.',
  '/category-images/cash-back.jpeg': 'Cartoon money and coins swirling around a glowing circle, representing cash back.',
  '/category-images/no-annual-fee.jpeg': 'Illustration of a credit card with a checkmark and 0$ for no annual fee.',
  '/category-images/travel-rewards.jpeg': 'Travel rewards header: Airplane with a passport, globe, compass, and credit card.',
  '/guides-images/building-credit.jpeg': 'Building Credit: Rising bar graph with arrow flag signifying growth.',
  '/guides-images/car-insurance-coverage-guide.jpeg': 'Car with damage, umbrella, and shield, symbolizing car insurance coverage.',
  '/guides-images/choose-credit-card.jpeg': 'Three colorful credit cards, a flowchart, and pen for choosing credit cards.',
  '/guides-images/credit-card-points-guide.jpeg': 'Blue credit card surrounded by travel and shopping icons on marble background.',
  '/guides-images/credit-score-101.jpeg': 'Credit score guide image with tablet displaying good rating and green graph.',
  '/guides-images/home-insurance-coverage-guide.jpeg': 'Home insurance coverage guide: umbrella protects house from damage and liability.',
  '/guides-images/life-insurance-explained.jpeg': 'Planning for life insurance: Notebook, pen, family photo, and potted plant.',
  '/guides-images/maximize-cashback.jpeg': 'Cash back credit card with coins flowing from it, financial benefits concept.',
  '/guides-images/renters-insurance-guide.jpeg': 'Flat lay of personal belongings; renters insurance protects your everyday items.',
  '/insurance-images/car-insurance.jpeg': 'White car on ocean road. Concept for comparing car insurance quotes.',
  '/insurance-images/home-insurance.jpeg': 'Well-lit suburban home at dusk representing the security of home insurance.',
  '/insurance-images/life-insurance.jpeg': 'Landscape with a large tree, bench, and sun, representing life insurance.',
  '/insurance-images/renters-insurance.jpeg': 'Cozy apartment living room with city view for renters insurance comparison.',
  '/insurance-heroes/car-insurance.jpeg': 'Blue car driving on highway, representing car insurance options.',
  '/news-images/american-airlines-flagship-suites.jpeg': 'American Airlines Flagship Suites interior, optimizing travel rewards points and miles.',
  '/news-images/amex-platinum-annual-fee.jpeg': 'Amex Platinum credit card, plane tickets, hotel key, and travel items.',
  '/news-images/chase-sapphire-reserve-benefits.jpeg': 'Chase Sapphire Reserve credit card and travel journal in airport lounge.',
  '/news-images/delta-skymiles-award-chart.jpeg': 'Airplane on runway at sunset, relevant to Delta SkyMiles travel rewards.',
  '/news-images/hilton-honors-devaluation.jpeg': 'Luxurious Hilton hotel room with city view. Use travel rewards effectively.',
  '/news-images/marriott-bonvoy-elite-status.jpeg': 'Luxury hotel lobby showcasing benefits of travel rewards credit cards.',
  '/team/david-kim.jpg': 'Screened.com team member David Kim, financial expert, wearing glasses, looking at camera.',
  '/team/emily-johnson.jpg': 'Emily Johnson, Screened.com financial expert, headshot in yellow blazer against office background.',
  '/team/james-wilson.jpg': 'Screened.com team member James Wilson headshot, expert in credit cards and personal finance.',
  '/team/jessica-martinez.jpg': 'Jessica Martinez headshot. Screened.com personal finance expert, smiling at the camera.',
  '/team/michael-rodriguez.jpg': 'Michael Rodriguez, Screened.com financial expert, headshot with beard, grey sweater, patterned shirt.',
  '/team/sarah-chen.jpg': 'Sarah Chen, Screened.com\'s expert on personal finance guides and credit card reviews.',
  '/icons/credit-card.png': 'Credit card icon with contactless symbol for financial services and rewards.',
  '/icons/deals.png': 'Deals icon: Percentage symbol inside tag, representing savings and financial discounts.',
  '/icons/hotel.png': 'Hotel building icon for travel rewards credit cards and travel insurance.',
  '/icons/newsletter.png': 'Newsletter icon: Open envelope with document, for financial advice and deals.',
  '/icons/travel.png': 'Airplane icon flying over globe, travel rewards and points optimization.',
  '/logo/screened-icon.png': 'Screened.com logo: A blue circle icon with the letter "S" inside.',
  '/logo/screened-logo.png': 'Screened.com logo. Helping you make smarter financial decisions with expert reviews.'
};

/**
 * Get optimized alt text for an image path
 * Falls back to extracting name from filename if not found
 */
export function getAltText(imagePath: string, fallback?: string): string {
  if (altTextMap[imagePath]) {
    return altTextMap[imagePath];
  }
  
  // Fallback: extract readable name from filename
  if (fallback) return fallback;
  
  const filename = imagePath.split('/').pop() || '';
  const name = filename.replace(/\.(png|jpg|jpeg|webp)$/i, '');
  return name.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}
