/**
 * Antivirus Logo Map
 * Auto-generated by scripts/fetch-all-logos.js
 * 
 * Usage:
 *   import { getAntivirusLogo } from '../utils/AntivirusLogoMap';
 *   const logoUrl = getAntivirusLogo('Company Name');
 */

export const antivirusLogos: Record<string, string> = {
  "Norton": "/antivirus-logos/norton.png",
  "norton": "/antivirus-logos/norton.png",
  "McAfee": "/antivirus-logos/mcafee.png",
  "mcafee": "/antivirus-logos/mcafee.png",
  "Bitdefender": "/antivirus-logos/bitdefender.png",
  "bitdefender": "/antivirus-logos/bitdefender.png",
  "Kaspersky": "/antivirus-logos/kaspersky.png",
  "kaspersky": "/antivirus-logos/kaspersky.png",
  "Avast": "/antivirus-logos/avast.png",
  "avast": "/antivirus-logos/avast.png",
  "AVG": "/antivirus-logos/avg.png",
  "avg": "/antivirus-logos/avg.png",
  "ESET": "/antivirus-logos/eset.png",
  "eset": "/antivirus-logos/eset.png",
  "Malwarebytes": "/antivirus-logos/malwarebytes.png",
  "malwarebytes": "/antivirus-logos/malwarebytes.png",
  "Trend Micro": "/antivirus-logos/trendmicro.png",
  "trendmicro": "/antivirus-logos/trendmicro.png",
  "trend micro": "/antivirus-logos/trendmicro.png",
  "Webroot": "/antivirus-logos/webroot.png",
  "webroot": "/antivirus-logos/webroot.png"
};

export function getAntivirusLogo(nameOrSlug: string): string | null {
  const key = nameOrSlug.toLowerCase();
  return antivirusLogos[key] || null;
}

export default antivirusLogos;
