/**
 * HomeWarranty Logo Map
 * Auto-generated by scripts/fetch-all-logos.js
 * 
 * Usage:
 *   import { getHomeWarrantyLogo } from '../utils/HomeWarrantyLogoMap';
 *   const logoUrl = getHomeWarrantyLogo('Company Name');
 */

export const homeWarrantyLogos: Record<string, string> = {
  "American Home Shield": "/home-warranty-logos/american-home-shield.png",
  "american-home-shield": "/home-warranty-logos/american-home-shield.png",
  "american home shield": "/home-warranty-logos/american-home-shield.png",
  "Choice Home Warranty": "/home-warranty-logos/choice.png",
  "choice": "/home-warranty-logos/choice.png",
  "choice home warranty": "/home-warranty-logos/choice.png",
  "Select Home Warranty": "/home-warranty-logos/select.png",
  "select": "/home-warranty-logos/select.png",
  "select home warranty": "/home-warranty-logos/select.png",
  "First American Home Warranty": "/home-warranty-logos/first-american.png",
  "first-american": "/home-warranty-logos/first-american.png",
  "first american home warranty": "/home-warranty-logos/first-american.png",
  "Liberty Home Guard": "/home-warranty-logos/liberty.png",
  "liberty": "/home-warranty-logos/liberty.png",
  "liberty home guard": "/home-warranty-logos/liberty.png",
  "Cinch Home Services": "/home-warranty-logos/cinch.png",
  "cinch": "/home-warranty-logos/cinch.png",
  "cinch home services": "/home-warranty-logos/cinch.png",
  "AFC Home Club": "/home-warranty-logos/afc.png",
  "afc": "/home-warranty-logos/afc.png",
  "afc home club": "/home-warranty-logos/afc.png",
  "Home Warranty of America": "/home-warranty-logos/hwa.png",
  "hwa": "/home-warranty-logos/hwa.png",
  "home warranty of america": "/home-warranty-logos/hwa.png",
  "2-10 Home Buyers Warranty": "/home-warranty-logos/2-10.png",
  "2-10": "/home-warranty-logos/2-10.png",
  "2-10 home buyers warranty": "/home-warranty-logos/2-10.png",
  "Landmark Home Warranty": "/home-warranty-logos/landmark.png",
  "landmark": "/home-warranty-logos/landmark.png",
  "landmark home warranty": "/home-warranty-logos/landmark.png"
};

export function getHomeWarrantyLogo(nameOrSlug: string): string | null {
  const key = nameOrSlug.toLowerCase();
  return homeWarrantyLogos[key] || null;
}

export default homeWarrantyLogos;
