/**
 * Mattress Logo Map
 * Auto-generated by scripts/fetch-all-logos.js
 * 
 * Usage:
 *   import { getMattressLogo } from '../utils/MattressLogoMap';
 *   const logoUrl = getMattressLogo('Company Name');
 */

export const mattressLogos: Record<string, string> = {
  "Saatva": "/mattress-logos/saatva.png",
  "saatva": "/mattress-logos/saatva.png",
  "Casper": "/mattress-logos/casper.png",
  "casper": "/mattress-logos/casper.png",
  "Purple": "/mattress-logos/purple.png",
  "purple": "/mattress-logos/purple.png",
  "Tempur-Pedic": "/mattress-logos/tempurpedic.png",
  "tempurpedic": "/mattress-logos/tempurpedic.png",
  "tempur-pedic": "/mattress-logos/tempurpedic.png",
  "Nectar": "/mattress-logos/nectar.png",
  "nectar": "/mattress-logos/nectar.png",
  "Helix": "/mattress-logos/helix.png",
  "helix": "/mattress-logos/helix.png",
  "DreamCloud": "/mattress-logos/dreamcloud.png",
  "dreamcloud": "/mattress-logos/dreamcloud.png",
  "Leesa": "/mattress-logos/leesa.png",
  "leesa": "/mattress-logos/leesa.png",
  "Brooklyn Bedding": "/mattress-logos/brooklyn-bedding.png",
  "brooklyn-bedding": "/mattress-logos/brooklyn-bedding.png",
  "brooklyn bedding": "/mattress-logos/brooklyn-bedding.png",
  "Avocado": "/mattress-logos/avocado.png",
  "avocado": "/mattress-logos/avocado.png",
  "Bear": "/mattress-logos/bear.png",
  "bear": "/mattress-logos/bear.png",
  "Tuft & Needle": "/mattress-logos/tuft-needle.png",
  "tuft-needle": "/mattress-logos/tuft-needle.png",
  "tuft & needle": "/mattress-logos/tuft-needle.png"
};

export function getMattressLogo(nameOrSlug: string): string | null {
  const key = nameOrSlug.toLowerCase();
  return mattressLogos[key] || null;
}

export default mattressLogos;
