/**
 * MealDelivery Logo Map
 * Auto-generated by scripts/fetch-all-logos.js
 * 
 * Usage:
 *   import { getMealDeliveryLogo } from '../utils/MealDeliveryLogoMap';
 *   const logoUrl = getMealDeliveryLogo('Company Name');
 */

export const mealDeliveryLogos: Record<string, string> = {
  "HelloFresh": "/meal-delivery-logos/hellofresh.png",
  "hellofresh": "/meal-delivery-logos/hellofresh.png",
  "Blue Apron": "/meal-delivery-logos/blue-apron.png",
  "blue-apron": "/meal-delivery-logos/blue-apron.png",
  "blue apron": "/meal-delivery-logos/blue-apron.png",
  "Home Chef": "/meal-delivery-logos/home-chef.png",
  "home-chef": "/meal-delivery-logos/home-chef.png",
  "home chef": "/meal-delivery-logos/home-chef.png",
  "Freshly": "/meal-delivery-logos/freshly.png",
  "freshly": "/meal-delivery-logos/freshly.png",
  "Factor": "/meal-delivery-logos/factor.png",
  "factor": "/meal-delivery-logos/factor.png",
  "Green Chef": "/meal-delivery-logos/green-chef.png",
  "green-chef": "/meal-delivery-logos/green-chef.png",
  "green chef": "/meal-delivery-logos/green-chef.png",
  "Sunbasket": "/meal-delivery-logos/sunbasket.png",
  "sunbasket": "/meal-delivery-logos/sunbasket.png",
  "EveryPlate": "/meal-delivery-logos/everyplate.png",
  "everyplate": "/meal-delivery-logos/everyplate.png",
  "Dinnerly": "/meal-delivery-logos/dinnerly.png",
  "dinnerly": "/meal-delivery-logos/dinnerly.png",
  "Gobble": "/meal-delivery-logos/gobble.png",
  "gobble": "/meal-delivery-logos/gobble.png",
  "Hungryroot": "/meal-delivery-logos/hungryroot.png",
  "hungryroot": "/meal-delivery-logos/hungryroot.png",
  "Marley Spoon": "/meal-delivery-logos/marley-spoon.png",
  "marley-spoon": "/meal-delivery-logos/marley-spoon.png",
  "marley spoon": "/meal-delivery-logos/marley-spoon.png"
};

export function getMealDeliveryLogo(nameOrSlug: string): string | null {
  const key = nameOrSlug.toLowerCase();
  return mealDeliveryLogos[key] || null;
}

export default mealDeliveryLogos;
