/**
 * Moving Logo Map
 * Auto-generated by scripts/fetch-all-logos.js
 * 
 * Usage:
 *   import { getMovingLogo } from '../utils/MovingLogoMap';
 *   const logoUrl = getMovingLogo('Company Name');
 */

export const movingLogos: Record<string, string> = {
  "International Van Lines": "/moving-logos/international-van-lines.png",
  "international-van-lines": "/moving-logos/international-van-lines.png",
  "international van lines": "/moving-logos/international-van-lines.png",
  "United Van Lines": "/moving-logos/united-van-lines.png",
  "united-van-lines": "/moving-logos/united-van-lines.png",
  "united van lines": "/moving-logos/united-van-lines.png",
  "Allied Van Lines": "/moving-logos/allied.png",
  "allied": "/moving-logos/allied.png",
  "allied van lines": "/moving-logos/allied.png",
  "North American Van Lines": "/moving-logos/north-american.png",
  "north-american": "/moving-logos/north-american.png",
  "north american van lines": "/moving-logos/north-american.png",
  "Mayflower": "/moving-logos/mayflower.png",
  "mayflower": "/moving-logos/mayflower.png",
  "Two Men and a Truck": "/moving-logos/two-men-truck.png",
  "two-men-truck": "/moving-logos/two-men-truck.png",
  "two men and a truck": "/moving-logos/two-men-truck.png",
  "College Hunks": "/moving-logos/college-hunks.png",
  "college-hunks": "/moving-logos/college-hunks.png",
  "college hunks": "/moving-logos/college-hunks.png",
  "PODS": "/moving-logos/pods.png",
  "pods": "/moving-logos/pods.png",
  "U-Pack": "/moving-logos/u-pack.png",
  "u-pack": "/moving-logos/u-pack.png",
  "JK Moving": "/moving-logos/jk-moving.png",
  "jk-moving": "/moving-logos/jk-moving.png",
  "jk moving": "/moving-logos/jk-moving.png"
};

export function getMovingLogo(nameOrSlug: string): string | null {
  const key = nameOrSlug.toLowerCase();
  return movingLogos[key] || null;
}

export default movingLogos;
