/**
 * PasswordManager Logo Map
 * Auto-generated by scripts/fetch-all-logos.js
 * 
 * Usage:
 *   import { getPasswordManagerLogo } from '../utils/PasswordManagerLogoMap';
 *   const logoUrl = getPasswordManagerLogo('Company Name');
 */

export const passwordManagerLogos: Record<string, string> = {
  "1Password": "/password-manager-logos/1password.png",
  "1password": "/password-manager-logos/1password.png",
  "LastPass": "/password-manager-logos/lastpass.png",
  "lastpass": "/password-manager-logos/lastpass.png",
  "Dashlane": "/password-manager-logos/dashlane.png",
  "dashlane": "/password-manager-logos/dashlane.png",
  "Bitwarden": "/password-manager-logos/bitwarden.png",
  "bitwarden": "/password-manager-logos/bitwarden.png",
  "NordPass": "/password-manager-logos/nordpass.png",
  "nordpass": "/password-manager-logos/nordpass.png",
  "Keeper": "/password-manager-logos/keeper.png",
  "keeper": "/password-manager-logos/keeper.png",
  "RoboForm": "/password-manager-logos/roboform.png",
  "roboform": "/password-manager-logos/roboform.png",
  "Zoho Vault": "/password-manager-logos/zoho-vault.png",
  "zoho-vault": "/password-manager-logos/zoho-vault.png",
  "zoho vault": "/password-manager-logos/zoho-vault.png",
  "Enpass": "/password-manager-logos/enpass.png",
  "enpass": "/password-manager-logos/enpass.png",
  "Sticky Password": "/password-manager-logos/sticky-password.png",
  "sticky-password": "/password-manager-logos/sticky-password.png",
  "sticky password": "/password-manager-logos/sticky-password.png"
};

export function getPasswordManagerLogo(nameOrSlug: string): string | null {
  const key = nameOrSlug.toLowerCase();
  return passwordManagerLogos[key] || null;
}

export default passwordManagerLogos;
