/**
 * PetInsurance Logo Map
 * Auto-generated by scripts/fetch-all-logos.js
 * 
 * Usage:
 *   import { getPetInsuranceLogo } from '../utils/PetInsuranceLogoMap';
 *   const logoUrl = getPetInsuranceLogo('Company Name');
 */

export const petInsuranceLogos: Record<string, string> = {
  "Lemonade": "/pet-insurance-logos/lemonade.png",
  "lemonade": "/pet-insurance-logos/lemonade.png",
  "Healthy Paws": "/pet-insurance-logos/healthy-paws.png",
  "healthy-paws": "/pet-insurance-logos/healthy-paws.png",
  "healthy paws": "/pet-insurance-logos/healthy-paws.png",
  "Embrace": "/pet-insurance-logos/embrace.png",
  "embrace": "/pet-insurance-logos/embrace.png",
  "Spot": "/pet-insurance-logos/spot.png",
  "spot": "/pet-insurance-logos/spot.png",
  "ASPCA": "/pet-insurance-logos/aspca.png",
  "aspca": "/pet-insurance-logos/aspca.png",
  "Pets Best": "/pet-insurance-logos/pets-best.png",
  "pets-best": "/pet-insurance-logos/pets-best.png",
  "pets best": "/pet-insurance-logos/pets-best.png",
  "Nationwide": "/pet-insurance-logos/nationwide.png",
  "nationwide": "/pet-insurance-logos/nationwide.png",
  "Figo": "/pet-insurance-logos/figo.png",
  "figo": "/pet-insurance-logos/figo.png",
  "Trupanion": "/pet-insurance-logos/trupanion.png",
  "trupanion": "/pet-insurance-logos/trupanion.png",
  "Pumpkin": "/pet-insurance-logos/pumpkin.png",
  "pumpkin": "/pet-insurance-logos/pumpkin.png",
  "ManyPets": "/pet-insurance-logos/manypets.png",
  "manypets": "/pet-insurance-logos/manypets.png",
  "Fetch": "/pet-insurance-logos/fetch.png",
  "fetch": "/pet-insurance-logos/fetch.png"
};

export function getPetInsuranceLogo(nameOrSlug: string): string | null {
  const key = nameOrSlug.toLowerCase();
  return petInsuranceLogos[key] || null;
}

export default petInsuranceLogos;
