/**
 * Savings Logo Map
 * Auto-generated by scripts/fetch-all-logos.js
 * 
 * Usage:
 *   import { getSavingsLogo } from '../utils/SavingsLogoMap';
 *   const logoUrl = getSavingsLogo('Company Name');
 */

export const savingsLogos: Record<string, string> = {
  "SoFi": "/bank-logos/sofi.png",
  "sofi": "/bank-logos/sofi.png",
  "Marcus by Goldman Sachs": "/bank-logos/marcus.png",
  "marcus": "/bank-logos/marcus.png",
  "marcus by goldman sachs": "/bank-logos/marcus.png",
  "Ally Bank": "/bank-logos/ally.png",
  "ally": "/bank-logos/ally.png",
  "ally bank": "/bank-logos/ally.png",
  "American Express": "/bank-logos/amex.png",
  "amex": "/bank-logos/amex.png",
  "american express": "/bank-logos/amex.png",
  "Capital One": "/bank-logos/capital-one.png",
  "capital-one": "/bank-logos/capital-one.png",
  "capital one": "/bank-logos/capital-one.png",
  "Discover": "/bank-logos/discover.png",
  "discover": "/bank-logos/discover.png",
  "Synchrony": "/bank-logos/synchrony.png",
  "synchrony": "/bank-logos/synchrony.png",
  "CIT Bank": "/bank-logos/cit.png",
  "cit": "/bank-logos/cit.png",
  "cit bank": "/bank-logos/cit.png",
  "Barclays": "/bank-logos/barclays.png",
  "barclays": "/bank-logos/barclays.png",
  "Wealthfront": "/bank-logos/wealthfront.png",
  "wealthfront": "/bank-logos/wealthfront.png",
  "Betterment": "/bank-logos/betterment.png",
  "betterment": "/bank-logos/betterment.png",
  "UFB Direct": "/bank-logos/ufb-direct.png",
  "ufb-direct": "/bank-logos/ufb-direct.png",
  "ufb direct": "/bank-logos/ufb-direct.png"
};

export function getSavingsLogo(nameOrSlug: string): string | null {
  const key = nameOrSlug.toLowerCase();
  return savingsLogos[key] || null;
}

export default savingsLogos;
