/**
 * Security Logo Map
 * Auto-generated by scripts/fetch-all-logos.js
 * 
 * Usage:
 *   import { getSecurityLogo } from '../utils/SecurityLogoMap';
 *   const logoUrl = getSecurityLogo('Company Name');
 */

export const securityLogos: Record<string, string> = {
  "ADT": "/security-logos/adt.png",
  "adt": "/security-logos/adt.png",
  "SimpliSafe": "/security-logos/simplisafe.png",
  "simplisafe": "/security-logos/simplisafe.png",
  "Vivint": "/security-logos/vivint.png",
  "vivint": "/security-logos/vivint.png",
  "Ring": "/security-logos/ring.png",
  "ring": "/security-logos/ring.png",
  "Frontpoint": "/security-logos/frontpoint.png",
  "frontpoint": "/security-logos/frontpoint.png",
  "Abode": "/security-logos/abode.png",
  "abode": "/security-logos/abode.png",
  "Cove": "/security-logos/cove.png",
  "cove": "/security-logos/cove.png",
  "Brinks Home": "/security-logos/brinks.png",
  "brinks": "/security-logos/brinks.png",
  "brinks home": "/security-logos/brinks.png",
  "Wyze": "/security-logos/wyze.png",
  "wyze": "/security-logos/wyze.png",
  "Eufy": "/security-logos/eufy.png",
  "eufy": "/security-logos/eufy.png"
};

export function getSecurityLogo(nameOrSlug: string): string | null {
  const key = nameOrSlug.toLowerCase();
  return securityLogos[key] || null;
}

export default securityLogos;
