/**
 * Vpn Logo Map
 * Auto-generated by scripts/fetch-all-logos.js
 * 
 * Usage:
 *   import { getVpnLogo } from '../utils/VpnLogoMap';
 *   const logoUrl = getVpnLogo('Company Name');
 */

export const vpnLogos: Record<string, string> = {
  "NordVPN": "/vpn-logos/nordvpn.png",
  "nordvpn": "/vpn-logos/nordvpn.png",
  "ExpressVPN": "/vpn-logos/expressvpn.png",
  "expressvpn": "/vpn-logos/expressvpn.png",
  "Surfshark": "/vpn-logos/surfshark.png",
  "surfshark": "/vpn-logos/surfshark.png",
  "CyberGhost": "/vpn-logos/cyberghost.png",
  "cyberghost": "/vpn-logos/cyberghost.png",
  "Private Internet Access": "/vpn-logos/pia.png",
  "pia": "/vpn-logos/pia.png",
  "private internet access": "/vpn-logos/pia.png",
  "ProtonVPN": "/vpn-logos/protonvpn.png",
  "protonvpn": "/vpn-logos/protonvpn.png",
  "IPVanish": "/vpn-logos/ipvanish.png",
  "ipvanish": "/vpn-logos/ipvanish.png",
  "Windscribe": "/vpn-logos/windscribe.png",
  "windscribe": "/vpn-logos/windscribe.png",
  "Mullvad": "/vpn-logos/mullvad.png",
  "mullvad": "/vpn-logos/mullvad.png",
  "TunnelBear": "/vpn-logos/tunnelbear.png",
  "tunnelbear": "/vpn-logos/tunnelbear.png"
};

export function getVpnLogo(nameOrSlug: string): string | null {
  const key = nameOrSlug.toLowerCase();
  return vpnLogos[key] || null;
}

export default vpnLogos;
